language: ruby
rvm:
  - 2.5.1
env:
  - DB=postgresql
cache: bundler
services:
  - postgresql
before_script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - psql -c 'create database pgapp_test;' -U postgres
script: bundle exec rspec
bundler_args: --binstubs=./bundler_stubs
